version: ~> 1.0
dist: bionic
language: minimal
# branches:
#   only:
#   - bakerydemo-thibaudcolas
#   - bakerydemo-thibaudcolas2
#   - bakerydemo-thibaudcolas3
#   - bakerydemo-thibaudcolas4
#   - bakerydemo-thibaudcolas5
install:
- echo 'There is no install step'
script:
- echo 'Automated deployment to Heroku'
# deploy:
#   provider: heroku
#   api_key:
#     # $ travis encrypt --pro $(heroku auth:token)
#     # Warning: token will expire 09/25/2021
#     secure: "CAwu8zSUpNdKEFvXWSYVK80V+0SVqGIiQJoKiJB/RbgBHBPNEInrmubtLi8OHu6hcwDuU3s8s8HekHrh6Wb5wZCZHWdRkx9rRwr5TxnEGb2CFCzeitkGHWkc08PELwLnbJ8FK6qK8D1ccv+TLZqcxzu++UzZ07n24OGU7zjasXKjF8TVYULSPUxW0llybX2zAzNPHSG+VpokSwpuPXTeYdmXVtg5+Cm90MwsByCnsQ04drLlzoKX6QUayxR3qGbgLRE37lKmRZW09ukVfC+f2ooP2yAsMTcpKKm1CZZ6N6Qu0lFE1218ZZjJ0+drusQP+h+eHgZxCxT1lY9uIa5wzGfljee5giuqAh/U8RISfUOktR+bNBFDASv788KsdQOztKNdzyKLWrE8LjR7INJcrv3j9go7DZ08UZmGEzw1gK1UDR2bG//QL34WWSkmZgvvxzj7xrvyO7VEU7rx19WZrv9T9Yp5Bn4uWMtjFevKGirZl4/+Uys6OyGcwIVohRk6lv9HW+DxQNP+81E4xz6IBka8gnkbRRdYxpjI+QwExz3B4KjwnzHPb6gSjGbDuz3BtFKsztY8k56LWj4nC897reyKRQLfwvFjKIajPDR/iFpjuzOAC8bAcIhf+f+553q8ZWxpNqJ2dQi8F0/ukyTWTFmg7W0ggpL0t7WsEDzk7m4="
#   app:
#     # bakerydemo-thibaudcolas: bakerydemo-thibaudcolas
#     bakerydemo-thibaudcolas2: bakerydemo-thibaudcolas2
#     bakerydemo-thibaudcolas3: bakerydemo-thibaudcolas3
#     bakerydemo-thibaudcolas4: bakerydemo-thibaudcolas4
#     bakerydemo-thibaudcolas5: bakerydemo-thibaudcolas5
notifications:
  email: false
