sudo: false
language: python
branches:
  only:
  - bakerydemo-thibaudcolas
  - bakerydemo-thibaudcolas2
  - bakerydemo-thibaudcolas3
  - bakerydemo-thibaudcolas4
  - bakerydemo-thibaudcolas5
install:
- echo 'There is no install step'
script:
- echo 'Automated deployment to Heroku'
deploy:
  provider: heroku
  api_key:
    # $ travis encrypt $(heroku auth:token)
    # Warning: token will expire 11/03/2019
    secure: ZmmSaR/r2A7qQnIuiU+LMtJkPcBElGrRQDJ+nGKEPK6MOzOPiDoLsKVSIJvkm8ZMyXfadeKiEzwEWdQckpwfB1OEhavLHA2Pas01YoYklfIUvPu0sd2ONes13L9SURGCvP9Lf2bgVu/NHNL+uUL2P2uh85MkOpCik4Rc2RfIH4qUpg6MBnEFdNggoMroOWaF7yaQ0SjPweK+kfKpxeZoaDeykMMsJP8psSAIWNzP38UsFHYOXIFoj0ui9d0C0HWvJ2B/xZZ5ztnUpiSxk0ZTNbt3QqW/Q8uMfS8UhcamOUbKQfqAm1Z9LqMkOYQxQGMTOuzkLqB8QfBsx1rDhl4xUnmM8P76qmzsdOGsLHPqJKrpTotY7vIUildxx6m5Ib+2sCQkVwYJqKaWYUFyci6XND+KqQAjGHbk9SZhTdUzVxiWQ2PkHiE7o6Ka+LzTKevC0UFugjoqDPSxloMbcyDruS1ufKypwJN95bVQcpOe4gqdPH73bDUWE0jXImpqeLt3jcTE4UlfuZMf1I3xgVhH32jVYDdD7Wj++tXBUbobDRJTMmZBCZpBywE4AemGwKKrPZkWSFNDfHv1RMjgDCGfJzT5CKuClxZoiloQ5/Hbv7J7c61yUixLsRhwkplZGZ4BWOcm7m7yexvy63NG9tnURmSDFhEQ0jQXzqrg5h2lUrM=
  app:
    bakerydemo-thibaudcolas: bakerydemo-thibaudcolas
    bakerydemo-thibaudcolas2: bakerydemo-thibaudcolas2
    bakerydemo-thibaudcolas3: bakerydemo-thibaudcolas3
    bakerydemo-thibaudcolas4: bakerydemo-thibaudcolas4
    bakerydemo-thibaudcolas5: bakerydemo-thibaudcolas5
notifications:
  email: false
