# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 22:05
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180128_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='introduction_demo',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
