# Generated by Django 5.0.11 on 2025-01-27 15:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0024_remove_homepage_footnotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="footnotes",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
